services:
  frontend:
    build:
      context: .
      dockerfile: ../docker/react/Dockerfile
    container_name: react
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
