version: '3.8'

services:
  # PHP-FPM Service
  app:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile  # Path to Dockerfile in the docker folder
    container_name: php-fpm
    volumes:
      - .:/var/www  # Map the backend folder to the container's /var/www/html
    networks:
      - laravel-network
    depends_on:
      - postgres

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ../docker/nginx.conf:/etc/nginx/nginx.conf  # Path to nginx.conf in the docker folder
      - .:/var/www  # Map the backend folder to the container's /var/www/html
    ports:
      - "8090:80"
    networks:
      - laravel-network
    depends_on:
      - app

  # PostgreSQL Service
  postgres:
    image: postgres:15.3
    container_name: postgres
    environment:
      POSTGRES_DB: '${DB_DATABASE}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_USER: '${DB_USERNAME}'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - laravel-network

# Volumes
volumes:
  postgres_data:

# Networks
networks:
  laravel-network:
    driver: bridge
